# SPDX-FileCopyrightText: 2023 - 2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Ensure Meilisearch paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ meilisearch_uid }}"
    group: "{{ meilisearch_gid }}"
  with_items:
    - "{{ meilisearch_base_path }}"
    - "{{ meilisearch_data_path }}"

- name: Ensure Meilisearch support files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ meilisearch_base_path }}/{{ item }}"
    mode: "0640"
    owner: "{{ meilisearch_uid }}"
    group: "{{ meilisearch_gid }}"
  with_items:
    - env
    - labels
  register: meilisearch_support_files_result

- name: Ensure Meilisearch container image is pulled via community.docker.docker_image
  when: sysd_docker_image_pull_method == 'ansible-module'
  community.docker.docker_image:
    name: "{{ meilisearch_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ meilisearch_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else meilisearch_container_image_force_pull }}"
  register: meilisearch_container_image_pull_result
  retries: "{{ container_retry }}"
  delay: "{{ container_retry_delay }}"
  until: meilisearch_container_image_pull_result is not failed

- name: Ensure Meilisearch container image is pulled via ansible.builtin.command
  when: sysd_docker_image_pull_method == 'command'
  ansible.builtin.command:
    cmd: "{{ sysd_docker_host_command }} pull {{ meilisearch_container_image }}"
  register: meilisearch_container_image_pull_result
  retries: "{{ container_retry }}"
  delay: "{{ container_retry_delay }}"
  until: meilisearch_container_image_pull_result is not failed
  changed_when: "'Downloaded newer image' in result.stdout"

- name: Ensure Meilisearch container network is created via community.docker.docker_network
  when: sysd_docker_net_creation_method == 'ansible-module'
  community.docker.docker_network:
    enable_ipv6: "{{ sysd_docker_ipv6_enabled }}"
    name: "{{ meilisearch_container_network }}"
    driver: bridge
    driver_options: "{{ sysd_docker_net_driver_opts }}"
  register: meilisearch_network_creation_result

- name: Ensure Meilisearch container network is created via ansible.builtin.command
  when: sysd_docker_net_creation_method == 'command'
  ansible.builtin.command:
    cmd: >-
      {{ sysd_docker_host_command }} network create
      {% if sysd_docker_ipv6_enabled %}--ipv6{% endif %}
      {{ sysd_docker_net_driver_opts_string }}
      {{ meilisearch_container_network }}
  register: meilisearch_network_creation_result
  changed_when: meilisearch_network_creation_result.rc == 0
  failed_when: meilisearch_network_creation_result.rc != 0 and 'already exists' not in meilisearch_network_creation_result.stderr

- name: Ensure Meilisearch systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/meilisearch.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ meilisearch_identifier }}.service"
    mode: "0644"
  register: meilisearch_systemd_service_result

- name: Determine whether Meilisearch needs a restart
  ansible.builtin.set_fact:
    meilisearch_restart_necessary: >-
      {{
        meilisearch_support_files_result.changed | default(false)
        or meilisearch_systemd_service_result.changed | default(false)
        or meilisearch_container_image_pull_result.changed | default(false)
      }}
